"""Handoff packet builder — creates context packets when tickets are reassigned."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from .tickets import Ticket


class HandoffBuilder:
    """Builds handoff documents when a ticket is reassigned from one agent to another.

    Handoffs are saved as Markdown files in data/handoffs/ so the receiving agent
    gets full context about what the previous agent accomplished.
    """

    def __init__(self, handoff_dir: str | Path):
        self.handoff_dir = Path(handoff_dir)
        self.handoff_dir.mkdir(parents=True, exist_ok=True)

    def create_handoff(
        self,
        ticket: Ticket,
        from_agent: str,
        to_agent: str,
        reason: str,
        partial_output: str = "",
        next_step: str = "",
    ) -> Path:
        """Create a handoff document for ticket reassignment.

        Returns the path to the created handoff file.
        """
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
        filename = f"ticket_{ticket.id}_{ts}.md"
        path = self.handoff_dir / filename

        content = f"""# Handoff: Ticket #{ticket.id} — {ticket.title}

## Transfer
- **From:** {from_agent}
- **To:** {to_agent}
- **Reason:** {reason}
- **Timestamp:** {datetime.now(timezone.utc).isoformat()}

## Ticket Details
- **Goal ID:** {ticket.goal_id}
- **Priority:** {ticket.priority.value if hasattr(ticket.priority, 'value') else ticket.priority}
- **State:** {ticket.state.value if hasattr(ticket.state, 'value') else ticket.state}
- **Description:** {ticket.description}
- **Acceptance Criteria:** {ticket.acceptance}
"""

        if ticket.depends_on:
            content += f"\n## Dependencies\nDepends on tickets: {ticket.depends_on}\n"

        if partial_output:
            content += f"\n## Partial Output from {from_agent}\n```\n{partial_output[:5000]}\n```\n"

        if next_step:
            content += f"\n## Suggested Next Step\n{next_step}\n"

        content += f"\n---\n_Generated by Council orchestrator_\n"

        path.write_text(content)
        return path

    def read_handoff(self, path: str | Path) -> str:
        """Read a handoff document."""
        p = Path(path)
        if p.exists():
            return p.read_text()
        return ""

    def list_handoffs(self, ticket_id: Optional[int] = None) -> list[Path]:
        """List handoff files, optionally filtered by ticket ID."""
        pattern = f"ticket_{ticket_id}_*.md" if ticket_id else "ticket_*.md"
        return sorted(self.handoff_dir.glob(pattern))

    def get_latest_handoff(self, ticket_id: int) -> Optional[str]:
        """Get the content of the most recent handoff for a ticket."""
        files = self.list_handoffs(ticket_id)
        if files:
            return files[-1].read_text()
        return None
